# Generated by Django 2.1.3 on 2018-11-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('image', models.FileField(max_length=250, null=True, upload_to='storage/images/')),
                ('navigation', models.CharField(max_length=100)),
            ],
        ),
    ]
